import type { NavigationItem } from '@/lib/supabase/types'

export const INTERNAL_PORTAL_NAVIGATION: NavigationItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/internal-portal/dashboard',
    icon: 'LayoutDashboard',
    roles: ['staff', 'admin'],
  },
  {
    id: 'queue',
    label: 'Queue Management',
    href: '/internal-portal/queue',
    icon: 'Users',
    roles: ['staff', 'admin'],
  },
  {
    id: 'requests',
    label: 'Customer Requests',
    href: '/internal-portal/requests',
    icon: 'FileText',
    roles: ['staff', 'admin'],
  },
  {
    id: 'customers',
    label: 'Customers',
    href: '/internal-portal/customers',
    icon: 'User',
    roles: ['staff', 'admin'],
  },
  {
    id: 'transactions',
    label: 'Transactions',
    href: '/internal-portal/transactions',
    icon: 'TrendingUp',
    roles: ['staff', 'admin'],
  },
  {
    id: 'kyc',
    label: 'KYC Verification',
    href: '/internal-portal/kyc',
    icon: 'CheckCircle',
    roles: ['staff', 'admin'],
  },
  {
    id: 'notifications',
    label: 'Notifications',
    href: '/internal-portal/notifications',
    icon: 'Bell',
    roles: ['staff', 'admin'],
  },
  {
    id: 'activity-log',
    label: 'Activity Log',
    href: '/internal-portal/activity-log',
    icon: 'History',
    roles: ['staff', 'admin'],
  },
  {
    id: 'profile',
    label: 'Profile',
    href: '/internal-portal/profile',
    icon: 'User',
    roles: ['staff', 'admin'],
  },
  // Admin-only sections
  {
    id: 'employees',
    label: 'Employee Management',
    href: '/internal-portal/employees',
    icon: 'Users',
    roles: ['admin'],
  },
  {
    id: 'analytics',
    label: 'Analytics',
    href: '/internal-portal/analytics',
    icon: 'BarChart',
    roles: ['admin'],
  },
  {
    id: 'reports',
    label: 'Reports',
    href: '/internal-portal/reports',
    icon: 'FileText',
    roles: ['admin'],
  },
  {
    id: 'branch',
    label: 'Branch Management',
    href: '/internal-portal/branch',
    icon: 'Building2',
    roles: ['admin'],
  },
  {
    id: 'kiosks',
    label: 'Kiosk Management',
    href: '/internal-portal/kiosks',
    icon: 'Zap',
    roles: ['admin'],
  },
  {
    id: 'devices',
    label: 'Device Management',
    href: '/internal-portal/devices',
    icon: 'Cpu',
    roles: ['admin'],
  },
  {
    id: 'settings',
    label: 'System Settings',
    href: '/internal-portal/settings',
    icon: 'Settings',
    roles: ['admin'],
  },
  {
    id: 'audit-logs',
    label: 'Audit Logs',
    href: '/internal-portal/audit-logs',
    icon: 'Shield',
    roles: ['admin'],
  },
]
